apiVersion: v1
kind: Pod
metadata:
  name: docs-loader-v2
  namespace: kubeflow
spec:
  restartPolicy: Never
  containers:
    - name: loader
      image: mysql:8.4
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: docs-volume
          mountPath: /data
  volumes:
    - name: docs-volume
      persistentVolumeClaim:
        claimName: kubeflow-docs-pvc
