cluster:
  enabled: false

standalone:
  enabled: true
  persistence:
    enabled: false
  podAnnotations:
    sidecar.istio.io/inject: "false"
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

etcd:
  replicaCount: 1
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

minio:
  mode: standalone
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

pulsar:
  enabled: false

pulsarv3:
  enabled: false
